import 'package:athkar/models/azkar_model.dart';
import 'package:flutter/material.dart';

Color kPrimaryCOlor = const Color(0xff48c549);
String kPrimaryFont = 'Almarai';
List<AzkarModel> ramdanlist = [
  AzkarModel(
      catname: "",
      count: 1,
      desc: "",
      ref: "",
      content: "يااااااارب",
      counter: 1),
  AzkarModel(
      catname: "",
      count: 1,
      desc: "",
      ref: "",
      content: " رمضان يااااااارب",
      counter: 1),
];
List<String> arshdad = [
  'أن لا يعتقد الراقي أن الرقية تؤثر بذاتها بل بذات الله سبحانه وتعالى',
  'كون الراقي والمرقي على طهارة تامة',
  'استقبال الراقي القبلة',
  'لزوم تدبر الراقي والمرقي لنصوص الرقية، فلا يقولها الراقي دون تفكر بمعانيها، ولا يستمعها المرقي إلا وقد اجتهد في تدبرها، واستحضر كلاهما الخشوع في أثناء الرقية بتعلق القلب بعظيم قدرة الله -تعالى- وحسن الاستعانة به سبحانه',
  'بإمكان الراقي الاقتصار في الرقية على الآيات القرآنية أو التعوذات النبوية، لكن الأكمل في ذلك أن يجمع بينها',
  'بإمكان الراقي أن يختار ما يناسب حسبما يتسع له وللمرقي الوقت، كما أن له الاختصار في الرقية، بحيث يختار منها ما يناسب حال المرقي، وللراقي كذلك قراءة الرقية على مراحل، بحيث يستريح المريض بينها',
  'النفث - وهو نفخ لطيف مع بعض ريق - في أثناء القراءة وبعدها، ولا بأس بتركه',
  'إن للراقي القراءة جهرا أو سرا، والجهر أولى، وذلك بصوت معتدل يتمكن معه المرقي من سماعه؛ فيزداد بذلك تأثره بالرقية وانتفاعه بها',
  'قد تستمر الرقية لمدة أسبوع كامل، وربما كانت أقل من ذلك، أو أكثر، وذلك بحسب حال المريض ومدى استجابته للعلاج، حتى يتم الشفاء بإذن الله',
  'إن لاحظ الراقي تأثر المريض ببعض الآيات في أثناء الرقية، فلا بأس بتكرارها ثلاثا، أو خمسا، أو سبع مرار، حسب الحاجة وملاحظة درجة الاستجابة'
];
List<String> quranlist = [
  'assets/quran/1.jpeg',
  'assets/quran/2.jpeg',
  'assets/quran/3.jpeg',
  'assets/quran/4.jpeg',
  'assets/quran/5.jpeg',
  'assets/quran/6.jpeg',
  'assets/quran/7.jpeg',
  'assets/quran/8.jpeg',
  'assets/quran/9.jpeg',
  'assets/quran/10.jpeg',
  'assets/quran/11.jpeg',
  'assets/quran/12.jpeg',
  'assets/quran/13.jpeg',
  'assets/quran/14.jpeg',
  'assets/quran/15.jpeg',
  'assets/quran/16.jpeg',
  'assets/quran/17.jpeg',
  'assets/quran/18.jpeg',
  'assets/quran/19.jpeg',
  'assets/quran/20.jpeg',
  'assets/quran/21.jpeg',
  'assets/quran/22.jpeg',
  'assets/quran/23.jpeg',
  'assets/quran/24.jpeg',
  'assets/quran/25.jpeg',
  'assets/quran/26.jpeg',
  'assets/quran/27.jpeg',
  'assets/quran/28.jpeg',
  'assets/quran/29.jpeg',
  'assets/quran/30.jpeg',
  'assets/quran/31.jpeg',
  'assets/quran/32.jpeg',
  'assets/quran/33.jpeg',
  'assets/quran/34.jpeg',
  'assets/quran/35.jpeg',
  'assets/quran/36.jpeg',
  'assets/quran/37.jpeg',
  'assets/quran/38.jpeg',
  'assets/quran/39.jpeg',
  'assets/quran/40.jpeg',
  'assets/quran/41.jpeg',
  'assets/quran/42.jpeg',
  'assets/quran/43.jpeg',
  'assets/quran/44.jpeg',
  'assets/quran/45.jpeg',
  'assets/quran/46.jpeg',
  'assets/quran/47.jpeg',
  'assets/quran/48.jpeg',
  'assets/quran/49.jpeg',
  'assets/quran/50.jpeg',
  'assets/quran/51.jpeg',
  'assets/quran/52.jpeg',
  'assets/quran/53.jpeg',
  'assets/quran/54.jpeg',
  'assets/quran/55.jpeg',
  'assets/quran/56.jpeg',
  'assets/quran/57.jpeg',
  'assets/quran/58.jpeg',
  'assets/quran/59.jpeg',
  'assets/quran/60.jpeg',
  'assets/quran/61.jpeg',
  'assets/quran/62.jpeg',
  'assets/quran/63.jpeg',
  'assets/quran/64.jpeg',
  'assets/quran/65.jpeg',
  'assets/quran/66.jpeg',
  'assets/quran/67.jpeg',
  'assets/quran/68.jpeg',
  'assets/quran/69.jpeg',
  'assets/quran/70.jpeg',
  'assets/quran/71.jpeg',
  'assets/quran/72.jpeg',
  'assets/quran/73.jpeg',
  'assets/quran/74.jpeg',
  'assets/quran/75.jpeg',
  'assets/quran/76.jpeg',
  'assets/quran/77.jpeg',
  'assets/quran/78.jpeg',
  'assets/quran/79.jpeg',
  'assets/quran/80.jpeg',
  'assets/quran/81.jpeg',
  'assets/quran/82.jpeg',
  'assets/quran/83.jpeg',
  'assets/quran/84.jpeg',
  'assets/quran/85.jpeg',
  'assets/quran/86.jpeg',
  'assets/quran/87.jpeg',
  'assets/quran/88.jpeg',
  'assets/quran/89.jpeg',
  'assets/quran/90.jpeg',
  'assets/quran/91.jpeg',
  'assets/quran/92.jpeg',
  'assets/quran/93.jpeg',
  'assets/quran/94.jpeg',
  'assets/quran/95.jpeg',
  'assets/quran/96.jpeg',
  'assets/quran/97.jpeg',
  'assets/quran/98.jpeg',
  'assets/quran/99.jpeg',
  'assets/quran/100.jpeg',
  'assets/quran/101.jpeg',
  'assets/quran/102.jpeg',
  'assets/quran/103.jpeg',
  'assets/quran/104.jpeg',
  'assets/quran/105.jpeg',
  'assets/quran/106.jpeg',
  'assets/quran/107.jpeg',
  'assets/quran/108.jpeg',
  'assets/quran/109.jpeg',
  'assets/quran/110.jpeg',
  'assets/quran/111.jpeg',
  'assets/quran/112.jpeg',
  'assets/quran/113.jpeg',
  'assets/quran/114.jpeg',
  'assets/quran/115.jpeg',
  'assets/quran/116.jpeg',
  'assets/quran/117.jpeg',
  'assets/quran/118.jpeg',
  'assets/quran/119.jpeg',
  'assets/quran/120.jpeg',
  'assets/quran/121.jpeg',
  'assets/quran/122.jpeg',
  'assets/quran/123.jpeg',
  'assets/quran/124.jpeg',
  'assets/quran/125.jpeg',
  'assets/quran/126.jpeg',
  'assets/quran/127.jpeg',
  'assets/quran/128.jpeg',
  'assets/quran/129.jpeg',
  'assets/quran/130.jpeg',
  'assets/quran/131.jpeg',
  'assets/quran/132.jpeg',
  'assets/quran/133.jpeg',
  'assets/quran/134.jpeg',
  'assets/quran/135.jpeg',
  'assets/quran/136.jpeg',
  'assets/quran/137.jpeg',
  'assets/quran/138.jpeg',
  'assets/quran/139.jpeg',
  'assets/quran/140.jpeg',
  'assets/quran/141.jpeg',
  'assets/quran/142.jpeg',
  'assets/quran/143.jpeg',
  'assets/quran/144.jpeg',
  'assets/quran/145.jpeg',
  'assets/quran/146.jpeg',
  'assets/quran/147.jpeg',
  'assets/quran/148.jpeg',
  'assets/quran/149.jpeg',
  'assets/quran/150.jpeg',
  'assets/quran/151.jpeg',
  'assets/quran/152.jpeg',
  'assets/quran/153.jpeg',
  'assets/quran/154.jpeg',
  'assets/quran/155.jpeg',
  'assets/quran/156.jpeg',
  'assets/quran/157.jpeg',
  'assets/quran/158.jpeg',
  'assets/quran/159.jpeg',
  'assets/quran/160.jpeg',
  'assets/quran/161.jpeg',
  'assets/quran/162.jpeg',
  'assets/quran/163.jpeg',
  'assets/quran/164.jpeg',
  'assets/quran/165.jpeg',
  'assets/quran/166.jpeg',
  'assets/quran/167.jpeg',
  'assets/quran/168.jpeg',
  'assets/quran/169.jpeg',
  'assets/quran/170.jpeg',
  'assets/quran/171.jpeg',
  'assets/quran/172.jpeg',
  'assets/quran/173.jpeg',
  'assets/quran/174.jpeg',
  'assets/quran/175.jpeg',
  'assets/quran/176.jpeg',
  'assets/quran/177.jpeg',
  'assets/quran/178.jpeg',
  'assets/quran/179.jpeg',
  'assets/quran/180.jpeg',
  'assets/quran/181.jpeg',
  'assets/quran/182.jpeg',
  'assets/quran/183.jpeg',
  'assets/quran/184.jpeg',
  'assets/quran/185.jpeg',
  'assets/quran/186.jpeg',
  'assets/quran/187.jpeg',
  'assets/quran/188.jpeg',
  'assets/quran/189.jpeg',
  'assets/quran/190.jpeg',
  'assets/quran/191.jpeg',
  'assets/quran/192.jpeg',
  'assets/quran/193.jpeg',
  'assets/quran/194.jpeg',
  'assets/quran/195.jpeg',
  'assets/quran/196.jpeg',
  'assets/quran/197.jpeg',
  'assets/quran/198.jpeg',
  'assets/quran/199.jpeg',
  'assets/quran/200.jpeg',
  'assets/quran/201.jpeg',
  'assets/quran/202.jpeg',
  'assets/quran/203.jpeg',
  'assets/quran/204.jpeg',
  'assets/quran/205.jpeg',
  'assets/quran/206.jpeg',
  'assets/quran/207.jpeg',
  'assets/quran/208.jpeg',
  'assets/quran/209.jpeg',
  'assets/quran/210.jpeg',
  'assets/quran/211.jpeg',
  'assets/quran/212.jpeg',
  'assets/quran/213.jpeg',
  'assets/quran/214.jpeg',
  'assets/quran/215.jpeg',
  'assets/quran/216.jpeg',
  'assets/quran/217.jpeg',
  'assets/quran/218.jpeg',
  'assets/quran/219.jpeg',
  'assets/quran/220.jpeg',
  'assets/quran/221.jpeg',
  'assets/quran/222.jpeg',
  'assets/quran/223.jpeg',
  'assets/quran/224.jpeg',
  'assets/quran/225.jpeg',
  'assets/quran/226.jpeg',
  'assets/quran/227.jpeg',
  'assets/quran/228.jpeg',
  'assets/quran/229.jpeg',
  'assets/quran/230.jpeg',
  'assets/quran/231.jpeg',
  'assets/quran/232.jpeg',
  'assets/quran/233.jpeg',
  'assets/quran/234.jpeg',
  'assets/quran/235.jpeg',
  'assets/quran/236.jpeg',
  'assets/quran/237.jpeg',
  'assets/quran/238.jpeg',
  'assets/quran/239.jpeg',
  'assets/quran/240.jpeg',
  'assets/quran/241.jpeg',
  'assets/quran/242.jpeg',
  'assets/quran/243.jpeg',
  'assets/quran/244.jpeg',
  'assets/quran/245.jpeg',
  'assets/quran/246.jpeg',
  'assets/quran/247.jpeg',
  'assets/quran/248.jpeg',
  'assets/quran/249.jpeg',
  'assets/quran/250.jpeg',
  'assets/quran/251.jpeg',
  'assets/quran/252.jpeg',
  'assets/quran/253.jpeg',
  'assets/quran/254.jpeg',
  'assets/quran/255.jpeg',
  'assets/quran/256.jpeg',
  'assets/quran/257.jpeg',
  'assets/quran/258.jpeg',
  'assets/quran/259.jpeg',
  'assets/quran/260.jpeg',
  'assets/quran/261.jpeg',
  'assets/quran/262.jpeg',
  'assets/quran/263.jpeg',
  'assets/quran/264.jpeg',
  'assets/quran/265.jpeg',
  'assets/quran/266.jpeg',
  'assets/quran/267.jpeg',
  'assets/quran/268.jpeg',
  'assets/quran/269.jpeg',
  'assets/quran/270.jpeg',
  'assets/quran/271.jpeg',
  'assets/quran/272.jpeg',
  'assets/quran/273.jpeg',
  'assets/quran/274.jpeg',
  'assets/quran/275.jpeg',
  'assets/quran/276.jpeg',
  'assets/quran/277.jpeg',
  'assets/quran/278.jpeg',
  'assets/quran/279.jpeg',
  'assets/quran/280.jpeg',
  'assets/quran/281.jpeg',
  'assets/quran/282.jpeg',
  'assets/quran/283.jpeg',
  'assets/quran/284.jpeg',
  'assets/quran/285.jpeg',
  'assets/quran/286.jpeg',
  'assets/quran/287.jpeg',
  'assets/quran/288.jpeg',
  'assets/quran/289.jpeg',
  'assets/quran/290.jpeg',
  'assets/quran/291.jpeg',
  'assets/quran/292.jpeg',
  'assets/quran/293.jpeg',
  'assets/quran/294.jpeg',
  'assets/quran/295.jpeg',
  'assets/quran/296.jpeg',
  'assets/quran/297.jpeg',
  'assets/quran/298.jpeg',
  'assets/quran/299.jpeg',
  'assets/quran/300.jpeg',
  'assets/quran/301.jpeg',
  'assets/quran/302.jpeg',
  'assets/quran/303.jpeg',
  'assets/quran/304.jpeg',
  'assets/quran/305.jpeg',
  'assets/quran/306.jpeg',
  'assets/quran/307.jpeg',
  'assets/quran/308.jpeg',
  'assets/quran/309.jpeg',
  'assets/quran/310.jpeg',
  'assets/quran/311.jpeg',
  'assets/quran/312.jpeg',
  'assets/quran/313.jpeg',
  'assets/quran/314.jpeg',
  'assets/quran/315.jpeg',
  'assets/quran/316.jpeg',
  'assets/quran/317.jpeg',
  'assets/quran/318.jpeg',
  'assets/quran/319.jpeg',
  'assets/quran/320.jpeg',
  'assets/quran/321.jpeg',
  'assets/quran/322.jpeg',
  'assets/quran/323.jpeg',
  'assets/quran/324.jpeg',
  'assets/quran/325.jpeg',
  'assets/quran/326.jpeg',
  'assets/quran/327.jpeg',
  'assets/quran/328.jpeg',
  'assets/quran/329.jpeg',
  'assets/quran/330.jpeg',
  'assets/quran/331.jpeg',
  'assets/quran/332.jpeg',
  'assets/quran/333.jpeg',
  'assets/quran/334.jpeg',
  'assets/quran/335.jpeg',
  'assets/quran/336.jpeg',
  'assets/quran/337.jpeg',
  'assets/quran/338.jpeg',
  'assets/quran/339.jpeg',
  'assets/quran/340.jpeg',
  'assets/quran/341.jpeg',
  'assets/quran/342.jpeg',
  'assets/quran/343.jpeg',
  'assets/quran/344.jpeg',
  'assets/quran/345.jpeg',
  'assets/quran/346.jpeg',
  'assets/quran/347.jpeg',
  'assets/quran/348.jpeg',
  'assets/quran/349.jpeg',
  'assets/quran/350.jpeg',
  'assets/quran/351.jpeg',
  'assets/quran/352.jpeg',
  'assets/quran/353.jpeg',
  'assets/quran/354.jpeg',
  'assets/quran/355.jpeg',
  'assets/quran/356.jpeg',
  'assets/quran/357.jpeg',
  'assets/quran/358.jpeg',
  'assets/quran/359.jpeg',
  'assets/quran/360.jpeg',
  'assets/quran/361.jpeg',
  'assets/quran/362.jpeg',
  'assets/quran/363.jpeg',
  'assets/quran/364.jpeg',
  'assets/quran/365.jpeg',
  'assets/quran/366.jpeg',
  'assets/quran/367.jpeg',
  'assets/quran/368.jpeg',
  'assets/quran/369.jpeg',
  'assets/quran/370.jpeg',
  'assets/quran/371.jpeg',
  'assets/quran/372.jpeg',
  'assets/quran/373.jpeg',
  'assets/quran/374.jpeg',
  'assets/quran/375.jpeg',
  'assets/quran/376.jpeg',
  'assets/quran/377.jpeg',
  'assets/quran/378.jpeg',
  'assets/quran/379.jpeg',
  'assets/quran/380.jpeg',
  'assets/quran/381.jpeg',
  'assets/quran/382.jpeg',
  'assets/quran/383.jpeg',
  'assets/quran/384.jpeg',
  'assets/quran/385.jpeg',
  'assets/quran/386.jpeg',
  'assets/quran/387.jpeg',
  'assets/quran/388.jpeg',
  'assets/quran/389.jpeg',
  'assets/quran/390.jpeg',
  'assets/quran/391.jpeg',
  'assets/quran/392.jpeg',
  'assets/quran/393.jpeg',
  'assets/quran/394.jpeg',
  'assets/quran/395.jpeg',
  'assets/quran/396.jpeg',
  'assets/quran/397.jpeg',
  'assets/quran/398.jpeg',
  'assets/quran/399.jpeg',
  'assets/quran/400.jpeg',
  'assets/quran/401.jpeg',
  'assets/quran/402.jpeg',
  'assets/quran/403.jpeg',
  'assets/quran/404.jpeg',
  'assets/quran/405.jpeg',
  'assets/quran/406.jpeg',
  'assets/quran/407.jpeg',
  'assets/quran/408.jpeg',
  'assets/quran/409.jpeg',
  'assets/quran/410.jpeg',
  'assets/quran/411.jpeg',
  'assets/quran/412.jpeg',
  'assets/quran/413.jpeg',
  'assets/quran/414.jpeg',
  'assets/quran/415.jpeg',
  'assets/quran/416.jpeg',
  'assets/quran/417.jpeg',
  'assets/quran/418.jpeg',
  'assets/quran/419.jpeg',
  'assets/quran/420.jpeg',
  'assets/quran/421.jpeg',
  'assets/quran/422.jpeg',
  'assets/quran/423.jpeg',
  'assets/quran/424.jpeg',
  'assets/quran/425.jpeg',
  'assets/quran/426.jpeg',
  'assets/quran/427.jpeg',
  'assets/quran/428.jpeg',
  'assets/quran/429.jpeg',
  'assets/quran/430.jpeg',
  'assets/quran/431.jpeg',
  'assets/quran/432.jpeg',
  'assets/quran/433.jpeg',
  'assets/quran/434.jpeg',
  'assets/quran/435.jpeg',
  'assets/quran/436.jpeg',
  'assets/quran/437.jpeg',
  'assets/quran/438.jpeg',
  'assets/quran/439.jpeg',
  'assets/quran/440.jpeg',
  'assets/quran/441.jpeg',
  'assets/quran/442.jpeg',
  'assets/quran/443.jpeg',
  'assets/quran/444.jpeg',
  'assets/quran/445.jpeg',
  'assets/quran/446.jpeg',
  'assets/quran/447.jpeg',
  'assets/quran/448.jpeg',
  'assets/quran/449.jpeg',
  'assets/quran/450.jpeg',
  'assets/quran/451.jpeg',
  'assets/quran/452.jpeg',
  'assets/quran/453.jpeg',
  'assets/quran/454.jpeg',
  'assets/quran/455.jpeg',
  'assets/quran/456.jpeg',
  'assets/quran/457.jpeg',
  'assets/quran/458.jpeg',
  'assets/quran/459.jpeg',
  'assets/quran/460.jpeg',
  'assets/quran/461.jpeg',
  'assets/quran/462.jpeg',
  'assets/quran/463.jpeg',
  'assets/quran/464.jpeg',
  'assets/quran/465.jpeg',
  'assets/quran/466.jpeg',
  'assets/quran/467.jpeg',
  'assets/quran/468.jpeg',
  'assets/quran/469.jpeg',
  'assets/quran/470.jpeg',
  'assets/quran/471.jpeg',
  'assets/quran/472.jpeg',
  'assets/quran/473.jpeg',
  'assets/quran/474.jpeg',
  'assets/quran/475.jpeg',
  'assets/quran/476.jpeg',
  'assets/quran/477.jpeg',
  'assets/quran/478.jpeg',
  'assets/quran/479.jpeg',
  'assets/quran/480.jpeg',
  'assets/quran/481.jpeg',
  'assets/quran/482.jpeg',
  'assets/quran/483.jpeg',
  'assets/quran/484.jpeg',
  'assets/quran/485.jpeg',
  'assets/quran/486.jpeg',
  'assets/quran/487.jpeg',
  'assets/quran/488.jpeg',
  'assets/quran/489.jpeg',
  'assets/quran/490.jpeg',
  'assets/quran/491.jpeg',
  'assets/quran/492.jpeg',
  'assets/quran/493.jpeg',
  'assets/quran/494.jpeg',
  'assets/quran/495.jpeg',
  'assets/quran/496.jpeg',
  'assets/quran/497.jpeg',
  'assets/quran/498.jpeg',
  'assets/quran/499.jpeg',
  'assets/quran/500.jpeg',
  'assets/quran/501.jpeg',
  'assets/quran/502.jpeg',
  'assets/quran/503.jpeg',
  'assets/quran/504.jpeg',
  'assets/quran/505.jpeg',
  'assets/quran/506.jpeg',
  'assets/quran/507.jpeg',
  'assets/quran/508.jpeg',
  'assets/quran/509.jpeg',
  'assets/quran/510.jpeg',
  'assets/quran/511.jpeg',
  'assets/quran/512.jpeg',
  'assets/quran/513.jpeg',
  'assets/quran/514.jpeg',
  'assets/quran/515.jpeg',
  'assets/quran/516.jpeg',
  'assets/quran/517.jpeg',
  'assets/quran/518.jpeg',
  'assets/quran/519.jpeg',
  'assets/quran/520.jpeg',
  'assets/quran/521.jpeg',
  'assets/quran/522.jpeg',
  'assets/quran/523.jpeg',
  'assets/quran/524.jpeg',
  'assets/quran/525.jpeg',
  'assets/quran/526.jpeg',
  'assets/quran/527.jpeg',
  'assets/quran/528.jpeg',
  'assets/quran/529.jpeg',
  'assets/quran/530.jpeg',
  'assets/quran/531.jpeg',
  'assets/quran/532.jpeg',
  'assets/quran/533.jpeg',
  'assets/quran/534.jpeg',
  'assets/quran/535.jpeg',
  'assets/quran/536.jpeg',
  'assets/quran/537.jpeg',
  'assets/quran/538.jpeg',
  'assets/quran/539.jpeg',
  'assets/quran/540.jpeg',
  'assets/quran/541.jpeg',
  'assets/quran/542.jpeg',
  'assets/quran/543.jpeg',
  'assets/quran/544.jpeg',
  'assets/quran/545.jpeg',
  'assets/quran/546.jpeg',
  'assets/quran/547.jpeg',
  'assets/quran/548.jpeg',
  'assets/quran/549.jpeg',
  'assets/quran/550.jpeg',
  'assets/quran/551.jpeg',
  'assets/quran/552.jpeg',
  'assets/quran/553.jpeg',
  'assets/quran/554.jpeg',
  'assets/quran/555.jpeg',
  'assets/quran/556.jpeg',
  'assets/quran/557.jpeg',
  'assets/quran/558.jpeg',
  'assets/quran/559.jpeg',
  'assets/quran/560.jpeg',
  'assets/quran/561.jpeg',
  'assets/quran/562.jpeg',
  'assets/quran/563.jpeg',
  'assets/quran/564.jpeg',
  'assets/quran/565.jpeg',
  'assets/quran/566.jpeg',
  'assets/quran/567.jpeg',
  'assets/quran/568.jpeg',
  'assets/quran/569.jpeg',
  'assets/quran/570.jpeg',
  'assets/quran/571.jpeg',
  'assets/quran/572.jpeg',
  'assets/quran/573.jpeg',
  'assets/quran/574.jpeg',
  'assets/quran/575.jpeg',
  'assets/quran/576.jpeg',
  'assets/quran/577.jpeg',
  'assets/quran/578.jpeg',
  'assets/quran/579.jpeg',
  'assets/quran/580.jpeg',
  'assets/quran/581.jpeg',
  'assets/quran/582.jpeg',
  'assets/quran/583.jpeg',
  'assets/quran/584.jpeg',
  'assets/quran/585.jpeg',
  'assets/quran/586.jpeg',
  'assets/quran/587.jpeg',
  'assets/quran/588.jpeg',
  'assets/quran/589.jpeg',
  'assets/quran/590.jpeg',
  'assets/quran/591.jpeg',
  'assets/quran/592.jpeg',
  'assets/quran/593.jpeg',
  'assets/quran/594.jpeg',
  'assets/quran/595.jpeg',
  'assets/quran/596.jpeg',
  'assets/quran/597.jpeg',
  'assets/quran/598.jpeg',
  'assets/quran/599.jpeg',
  'assets/quran/600.jpeg',
  'assets/quran/601.jpeg',
  'assets/quran/602.jpeg',
  'assets/quran/603.jpeg',
  'assets/quran/604.jpeg'
];
List<String> surahs = [
  'الفاتحة - Al-Fatiha',
  'البقرة - Al-Baqarah',
  'آل عمران - Aal-E-Imran',
  'النساء - An-Nisa\'',
  'المائدة - Al-Ma\'idah',
  'الأنعام - Al-An\'am',
  'الأعراف - Al-A\'raf',
  'الأنفال - Al-Anfal',
  'التوبة - At-Tawbah',
  'يونس - Yunus',
  'هود - Hud',
  'يوسف - Yusuf',
  'الرعد - Ar-Ra\'d',
  'إبراهيم - Ibrahim',
  'الحجر - Al-Hijr',
  'النحل - An-Nahl',
  'الإسراء - Al-Isra\'',
  'الكهف - Al-Kahf',
  'مريم - Maryam',
  'طه - Ta-Ha',
  'الأنبياء - Al-Anbiya\'',
  'الحج - Al-Hajj',
  'المؤمنون - Al-Mu\'minun',
  'النور - An-Nur',
  'الفرقان - Al-Furqan',
  'الشعراء - Ash-Shu\'ara\'',
  'النمل - An-Naml',
  'القصص - Al-Qasas',
  'العنكبوت - Al-Ankabut',
  'الرّوم - Ar-Rum',
  'لقمان - Luqman',
  'السجدة - As-Sajda',
  'الأحزاب - Al-Ahzab',
  'سبأ - Saba\'',
  'فاطر - Fatir',
  'يس - Ya-Sin',
  'الصافات - As-Saffat',
  'ص - Sad',
  'الزمر - Az-Zumar',
  'غافر - Ghafir',
  'فصلت - Fussilat',
  'الشورى - Ash-Shura',
  'الزخرف - Az-Zukhruf',
  'الدخان - Ad-Dukhan',
  'الجاثية - Al-Jathiyah',
  'الأحقاف - Al-Ahqaf',
  'محمد - Muhammad',
  'الفتح - Al-Fath',
  'الحجرات - Al-Hujurat',
  'ق - Qaf',
  'الذاريات - Adh-Dhariyat',
  'الطور - At-Tur',
  'النجم - An-Najm',
  'القمر - Al-Qamar',
  'الرحمن - Ar-Rahman',
  'الواقعة - Al-Waqi\'a',
  'الحديد - Al-Hadid',
  'المجادلة - Al-Mujadila',
  'الحشر - Al-Hashr',
  'الممتحنة - Al-Mumtahanah',
  'الصف - As-Saff',
  'الجمعة - Al-Jumu\'ah',
  'المنافقون - Al-Munafiqun',
  'التغابن - At-Taghabun',
  'الطلاق - At-Talaq',
  'التحريم - At-Tahrim',
  'الملك - Al-Mulk',
  'القلم - Al-Qalam',
  'الحاقة - Al-Haaqqa',
  'المعارج - Al-Ma\'arij',
  'نوح - Nuh',
  'الجن - Al-Jinn',
  'المزمل - Al-Muzzammil',
  'المدثر - Al-Muddathir',
  'القيامة - Al-Qiyama',
  'الإنسان - Al-Insan',
  'المرسلات - Al-Mursalat',
  'النبأ - An-Naba\'',
  'النازعات - An-Nazi\'at',
  'عبس - Abasa',
  'التكوير - At-Takwir',
  'الإنفطار - Al-Infitar',
  'المطففين - Al-Mutaffifin',
  'الإنشقاق - Al-Inshiqaq',
  'البروج - Al-Buruj',
  'الطارق - At-Tariq',
  'الأعلى - Al-A\'la',
  'الغاشية - Al-Ghashiyah',
  'الفجر - Al-Fajr',
  'البلد - Al-Balad',
  'الشمس - Ash-Shams',
  'الليل - Al-Lail',
  'الضحى - Ad-Duha',
  'الشرح - Ash-Sharh',
  'التين - At-Tin',
  'العلق - Al-Alaq',
  'القدر - Al-Qadr',
  'البينة - Al-Bayyina',
  'الزلزلة - Az-Zalzalah',
  'العاديات - Al-Adiyat',
  'القارعة - Al-Qari\'a',
  'التكاثر - At-Takathur',
  'العصر - Al-Asr',
  'الهمزة - Al-Humazah',
  'الفيل - Al-Fil',
  'قريش - Quraysh',
  'الماعون - Al-Ma\'un',
  'الكوثر - Al-Kawthar',
  'الكافرون - Al-Kafirun',
  'النصر - An-Nasr',
  'المسد - Al-Masad',
  'الإخلاص - Al-Ikhlas',
  'الفلق - Al-Falaq',
  'الناس - An-Nas'
];
List numberpagesurah = [
  1,
  2,
  50,
  77,
  106,
  128,
  151,
  177,
  187,
  208,
  221,
  235,
  249,
  255,
  262,
  267,
  282,
  293,
  305,
  312,
  322,
  332,
  342,
  350,
  359,
  367,
  377,
  385,
  396,
  404,
  411,
  415,
  418,
  428,
  434,
  440,
  446,
  453,
  458,
  467,
  477,
  483,
  489,
  496,
  499,
  502,
  507,
  511,
  515,
  518,
  520,
  523,
  526,
  528,
  531,
  534,
  537,
  542,
  545,
  549,
  551,
  553,
  554,
  556,
  558,
  560,
  562,
  564,
  566,
  568,
  570,
  572,
  574,
  575,
  577,
  578,
  580,
  582,
  583,
  585,
  586,
  587,
  587,
  589,
  590,
  591,
  591,
  592,
  593,
  594,
  595,
  595,
  596,
  596,
  597,
  597,
  598,
  598,
  599,
  599,
  600,
  600,
  601,
  601,
  601,
  602,
  602,
  602,
  603,
  603,
  603,
  604,
  604,
  604,
];
