import 'package:athkar/models/azkar_model.dart';
import 'package:flutter/material.dart';

Color kPrimaryCOlor = const Color(0xff48c549);
String kPrimaryFont = 'Almarai';
List<AzkarModel> ramdanlist = [
  AzkarModel(
      catname: "",
      count: 1,
      desc: "",
      ref: "",
      content: "يااااااارب",
      counter: 1),
  AzkarModel(
      catname: "",
      count: 1,
      desc: "",
      ref: "",
      content: " رمضان يااااااارب",
      counter: 1),
];
List<String> arshdad = [
  'أن لا يعتقد الراقي أن الرقية تؤثر بذاتها بل بذات الله سبحانه وتعالى',
  'كون الراقي والمرقي على طهارة تامة',
  'استقبال الراقي القبلة',
  'لزوم تدبر الراقي والمرقي لنصوص الرقية، فلا يقولها الراقي دون تفكر بمعانيها، ولا يستمعها المرقي إلا وقد اجتهد في تدبرها، واستحضر كلاهما الخشوع في أثناء الرقية بتعلق القلب بعظيم قدرة الله -تعالى- وحسن الاستعانة به سبحانه',
  'بإمكان الراقي الاقتصار في الرقية على الآيات القرآنية أو التعوذات النبوية، لكن الأكمل في ذلك أن يجمع بينها',
  'بإمكان الراقي أن يختار ما يناسب حسبما يتسع له وللمرقي الوقت، كما أن له الاختصار في الرقية، بحيث يختار منها ما يناسب حال المرقي، وللراقي كذلك قراءة الرقية على مراحل، بحيث يستريح المريض بينها',
  'النفث - وهو نفخ لطيف مع بعض ريق - في أثناء القراءة وبعدها، ولا بأس بتركه',
  'إن للراقي القراءة جهرا أو سرا، والجهر أولى، وذلك بصوت معتدل يتمكن معه المرقي من سماعه؛ فيزداد بذلك تأثره بالرقية وانتفاعه بها',
  'قد تستمر الرقية لمدة أسبوع كامل، وربما كانت أقل من ذلك، أو أكثر، وذلك بحسب حال المريض ومدى استجابته للعلاج، حتى يتم الشفاء بإذن الله',
  'إن لاحظ الراقي تأثر المريض ببعض الآيات في أثناء الرقية، فلا بأس بتكرارها ثلاثا، أو خمسا، أو سبع مرار، حسب الحاجة وملاحظة درجة الاستجابة'
];
List<String> quranlist = [
  'assets/quran/1.jpg',
  'assets/quran/2.jpg',
  'assets/quran/3.jpg',
  'assets/quran/4.jpg',
  'assets/quran/5.jpg',
  'assets/quran/6.jpg',
  'assets/quran/7.jpg',
  'assets/quran/8.jpg',
  'assets/quran/9.jpg',
  'assets/quran/10.jpg',
  'assets/quran/11.jpg',
  'assets/quran/12.jpg',
  'assets/quran/13.jpg',
  'assets/quran/14.jpg',
  'assets/quran/15.jpg',
  'assets/quran/16.jpg',
  'assets/quran/17.jpg',
  'assets/quran/18.jpg',
  'assets/quran/19.jpg',
  'assets/quran/20.jpg',
  'assets/quran/21.jpg',
  'assets/quran/22.jpg',
  'assets/quran/23.jpg',
  'assets/quran/24.jpg',
  'assets/quran/25.jpg',
  'assets/quran/26.jpg',
  'assets/quran/27.jpg',
  'assets/quran/28.jpg',
  'assets/quran/29.jpg',
  'assets/quran/30.jpg',
  'assets/quran/31.jpg',
  'assets/quran/32.jpg',
  'assets/quran/33.jpg',
  'assets/quran/34.jpg',
  'assets/quran/35.jpg',
  'assets/quran/36.jpg',
  'assets/quran/37.jpg',
  'assets/quran/38.jpg',
  'assets/quran/39.jpg',
  'assets/quran/40.jpg',
  'assets/quran/41.jpg',
  'assets/quran/42.jpg',
  'assets/quran/43.jpg',
  'assets/quran/44.jpg',
  'assets/quran/45.jpg',
  'assets/quran/46.jpg',
  'assets/quran/47.jpg',
  'assets/quran/48.jpg',
  'assets/quran/49.jpg',
  'assets/quran/50.jpg',
  'assets/quran/51.jpg',
  'assets/quran/52.jpg',
  'assets/quran/53.jpg',
  'assets/quran/54.jpg',
  'assets/quran/55.jpg',
  'assets/quran/56.jpg',
  'assets/quran/57.jpg',
  'assets/quran/58.jpg',
  'assets/quran/59.jpg',
  'assets/quran/60.jpg',
  'assets/quran/61.jpg',
  'assets/quran/62.jpg',
  'assets/quran/63.jpg',
  'assets/quran/64.jpg',
  'assets/quran/65.jpg',
  'assets/quran/66.jpg',
  'assets/quran/67.jpg',
  'assets/quran/68.jpg',
  'assets/quran/69.jpg',
  'assets/quran/70.jpg',
  'assets/quran/71.jpg',
  'assets/quran/72.jpg',
  'assets/quran/73.jpg',
  'assets/quran/74.jpg',
  'assets/quran/75.jpg',
  'assets/quran/76.jpg',
  'assets/quran/77.jpg',
  'assets/quran/78.jpg',
  'assets/quran/79.jpg',
  'assets/quran/80.jpg',
  'assets/quran/81.jpg',
  'assets/quran/82.jpg',
  'assets/quran/83.jpg',
  'assets/quran/84.jpg',
  'assets/quran/85.jpg',
  'assets/quran/86.jpg',
  'assets/quran/87.jpg',
  'assets/quran/88.jpg',
  'assets/quran/89.jpg',
  'assets/quran/90.jpg',
  'assets/quran/91.jpg',
  'assets/quran/92.jpg',
  'assets/quran/93.jpg',
  'assets/quran/94.jpg',
  'assets/quran/95.jpg',
  'assets/quran/96.jpg',
  'assets/quran/97.jpg',
  'assets/quran/98.jpg',
  'assets/quran/99.jpg',
  'assets/quran/100.jpg',
  'assets/quran/101.jpg',
  'assets/quran/102.jpg',
  'assets/quran/103.jpg',
  'assets/quran/104.jpg',
  'assets/quran/105.jpg',
  'assets/quran/106.jpg',
  'assets/quran/107.jpg',
  'assets/quran/108.jpg',
  'assets/quran/109.jpg',
  'assets/quran/110.jpg',
  'assets/quran/111.jpg',
  'assets/quran/112.jpg',
  'assets/quran/113.jpg',
  'assets/quran/114.jpg',
  'assets/quran/115.jpg',
  'assets/quran/116.jpg',
  'assets/quran/117.jpg',
  'assets/quran/118.jpg',
  'assets/quran/119.jpg',
  'assets/quran/120.jpg',
  'assets/quran/121.jpg',
  'assets/quran/122.jpg',
  'assets/quran/123.jpg',
  'assets/quran/124.jpg',
  'assets/quran/125.jpg',
  'assets/quran/126.jpg',
  'assets/quran/127.jpg',
  'assets/quran/128.jpg',
  'assets/quran/129.jpg',
  'assets/quran/130.jpg',
  'assets/quran/131.jpg',
  'assets/quran/132.jpg',
  'assets/quran/133.jpg',
  'assets/quran/134.jpg',
  'assets/quran/135.jpg',
  'assets/quran/136.jpg',
  'assets/quran/137.jpg',
  'assets/quran/138.jpg',
  'assets/quran/139.jpg',
  'assets/quran/140.jpg',
  'assets/quran/141.jpg',
  'assets/quran/142.jpg',
  'assets/quran/143.jpg',
  'assets/quran/144.jpg',
  'assets/quran/145.jpg',
  'assets/quran/146.jpg',
  'assets/quran/147.jpg',
  'assets/quran/148.jpg',
  'assets/quran/149.jpg',
  'assets/quran/150.jpg',
  'assets/quran/151.jpg',
  'assets/quran/152.jpg',
  'assets/quran/153.jpg',
  'assets/quran/154.jpg',
  'assets/quran/155.jpg',
  'assets/quran/156.jpg',
  'assets/quran/157.jpg',
  'assets/quran/158.jpg',
  'assets/quran/159.jpg',
  'assets/quran/160.jpg',
  'assets/quran/161.jpg',
  'assets/quran/162.jpg',
  'assets/quran/163.jpg',
  'assets/quran/164.jpg',
  'assets/quran/165.jpg',
  'assets/quran/166.jpg',
  'assets/quran/167.jpg',
  'assets/quran/168.jpg',
  'assets/quran/169.jpg',
  'assets/quran/170.jpg',
  'assets/quran/171.jpg',
  'assets/quran/172.jpg',
  'assets/quran/173.jpg',
  'assets/quran/174.jpg',
  'assets/quran/175.jpg',
  'assets/quran/176.jpg',
  'assets/quran/177.jpg',
  'assets/quran/178.jpg',
  'assets/quran/179.jpg',
  'assets/quran/180.jpg',
  'assets/quran/181.jpg',
  'assets/quran/182.jpg',
  'assets/quran/183.jpg',
  'assets/quran/184.jpg',
  'assets/quran/185.jpg',
  'assets/quran/186.jpg',
  'assets/quran/187.jpg',
  'assets/quran/188.jpg',
  'assets/quran/189.jpg',
  'assets/quran/190.jpg',
  'assets/quran/191.jpg',
  'assets/quran/192.jpg',
  'assets/quran/193.jpg',
  'assets/quran/194.jpg',
  'assets/quran/195.jpg',
  'assets/quran/196.jpg',
  'assets/quran/197.jpg',
  'assets/quran/198.jpg',
  'assets/quran/199.jpg',
  'assets/quran/200.jpg',
  'assets/quran/201.jpg',
  'assets/quran/202.jpg',
  'assets/quran/203.jpg',
  'assets/quran/204.jpg',
  'assets/quran/205.jpg',
  'assets/quran/206.jpg',
  'assets/quran/207.jpg',
  'assets/quran/208.jpg',
  'assets/quran/209.jpg',
  'assets/quran/210.jpg',
  'assets/quran/211.jpg',
  'assets/quran/212.jpg',
  'assets/quran/213.jpg',
  'assets/quran/214.jpg',
  'assets/quran/215.jpg',
  'assets/quran/216.jpg',
  'assets/quran/217.jpg',
  'assets/quran/218.jpg',
  'assets/quran/219.jpg',
  'assets/quran/220.jpg',
  'assets/quran/221.jpg',
  'assets/quran/222.jpg',
  'assets/quran/223.jpg',
  'assets/quran/224.jpg',
  'assets/quran/225.jpg',
  'assets/quran/226.jpg',
  'assets/quran/227.jpg',
  'assets/quran/228.jpg',
  'assets/quran/229.jpg',
  'assets/quran/230.jpg',
  'assets/quran/231.jpg',
  'assets/quran/232.jpg',
  'assets/quran/233.jpg',
  'assets/quran/234.jpg',
  'assets/quran/235.jpg',
  'assets/quran/236.jpg',
  'assets/quran/237.jpg',
  'assets/quran/238.jpg',
  'assets/quran/239.jpg',
  'assets/quran/240.jpg',
  'assets/quran/241.jpg',
  'assets/quran/242.jpg',
  'assets/quran/243.jpg',
  'assets/quran/244.jpg',
  'assets/quran/245.jpg',
  'assets/quran/246.jpg',
  'assets/quran/247.jpg',
  'assets/quran/248.jpg',
  'assets/quran/249.jpg',
  'assets/quran/250.jpg',
  'assets/quran/251.jpg',
  'assets/quran/252.jpg',
  'assets/quran/253.jpg',
  'assets/quran/254.jpg',
  'assets/quran/255.jpg',
  'assets/quran/256.jpg',
  'assets/quran/257.jpg',
  'assets/quran/258.jpg',
  'assets/quran/259.jpg',
  'assets/quran/260.jpg',
  'assets/quran/261.jpg',
  'assets/quran/262.jpg',
  'assets/quran/263.jpg',
  'assets/quran/264.jpg',
  'assets/quran/265.jpg',
  'assets/quran/266.jpg',
  'assets/quran/267.jpg',
  'assets/quran/268.jpg',
  'assets/quran/269.jpg',
  'assets/quran/270.jpg',
  'assets/quran/271.jpg',
  'assets/quran/272.jpg',
  'assets/quran/273.jpg',
  'assets/quran/274.jpg',
  'assets/quran/275.jpg',
  'assets/quran/276.jpg',
  'assets/quran/277.jpg',
  'assets/quran/278.jpg',
  'assets/quran/279.jpg',
  'assets/quran/280.jpg',
  'assets/quran/281.jpg',
  'assets/quran/282.jpg',
  'assets/quran/283.jpg',
  'assets/quran/284.jpg',
  'assets/quran/285.jpg',
  'assets/quran/286.jpg',
  'assets/quran/287.jpg',
  'assets/quran/288.jpg',
  'assets/quran/289.jpg',
  'assets/quran/290.jpg',
  'assets/quran/291.jpg',
  'assets/quran/292.jpg',
  'assets/quran/293.jpg',
  'assets/quran/294.jpg',
  'assets/quran/295.jpg',
  'assets/quran/296.jpg',
  'assets/quran/297.jpg',
  'assets/quran/298.jpg',
  'assets/quran/299.jpg',
  'assets/quran/300.jpg',
  'assets/quran/301.jpg',
  'assets/quran/302.jpg',
  'assets/quran/303.jpg',
  'assets/quran/304.jpg',
  'assets/quran/305.jpg',
  'assets/quran/306.jpg',
  'assets/quran/307.jpg',
  'assets/quran/308.jpg',
  'assets/quran/309.jpg',
  'assets/quran/310.jpg',
  'assets/quran/311.jpg',
  'assets/quran/312.jpg',
  'assets/quran/313.jpg',
  'assets/quran/314.jpg',
  'assets/quran/315.jpg',
  'assets/quran/316.jpg',
  'assets/quran/317.jpg',
  'assets/quran/318.jpg',
  'assets/quran/319.jpg',
  'assets/quran/320.jpg',
  'assets/quran/321.jpg',
  'assets/quran/322.jpg',
  'assets/quran/323.jpg',
  'assets/quran/324.jpg',
  'assets/quran/325.jpg',
  'assets/quran/326.jpg',
  'assets/quran/327.jpg',
  'assets/quran/328.jpg',
  'assets/quran/329.jpg',
  'assets/quran/330.jpg',
  'assets/quran/331.jpg',
  'assets/quran/332.jpg',
  'assets/quran/333.jpg',
  'assets/quran/334.jpg',
  'assets/quran/335.jpg',
  'assets/quran/336.jpg',
  'assets/quran/337.jpg',
  'assets/quran/338.jpg',
  'assets/quran/339.jpg',
  'assets/quran/340.jpg',
  'assets/quran/341.jpg',
  'assets/quran/342.jpg',
  'assets/quran/343.jpg',
  'assets/quran/344.jpg',
  'assets/quran/345.jpg',
  'assets/quran/346.jpg',
  'assets/quran/347.jpg',
  'assets/quran/348.jpg',
  'assets/quran/349.jpg',
  'assets/quran/350.jpg',
  'assets/quran/351.jpg',
  'assets/quran/352.jpg',
  'assets/quran/353.jpg',
  'assets/quran/354.jpg',
  'assets/quran/355.jpg',
  'assets/quran/356.jpg',
  'assets/quran/357.jpg',
  'assets/quran/358.jpg',
  'assets/quran/359.jpg',
  'assets/quran/360.jpg',
  'assets/quran/361.jpg',
  'assets/quran/362.jpg',
  'assets/quran/363.jpg',
  'assets/quran/364.jpg',
  'assets/quran/365.jpg',
  'assets/quran/366.jpg',
  'assets/quran/367.jpg',
  'assets/quran/368.jpg',
  'assets/quran/369.jpg',
  'assets/quran/370.jpg',
  'assets/quran/371.jpg',
  'assets/quran/372.jpg',
  'assets/quran/373.jpg',
  'assets/quran/374.jpg',
  'assets/quran/375.jpg',
  'assets/quran/376.jpg',
  'assets/quran/377.jpg',
  'assets/quran/378.jpg',
  'assets/quran/379.jpg',
  'assets/quran/380.jpg',
  'assets/quran/381.jpg',
  'assets/quran/382.jpg',
  'assets/quran/383.jpg',
  'assets/quran/384.jpg',
  'assets/quran/385.jpg',
  'assets/quran/386.jpg',
  'assets/quran/387.jpg',
  'assets/quran/388.jpg',
  'assets/quran/389.jpg',
  'assets/quran/390.jpg',
  'assets/quran/391.jpg',
  'assets/quran/392.jpg',
  'assets/quran/393.jpg',
  'assets/quran/394.jpg',
  'assets/quran/395.jpg',
  'assets/quran/396.jpg',
  'assets/quran/397.jpg',
  'assets/quran/398.jpg',
  'assets/quran/399.jpg',
  'assets/quran/400.jpg',
  'assets/quran/401.jpg',
  'assets/quran/402.jpg',
  'assets/quran/403.jpg',
  'assets/quran/404.jpg',
  'assets/quran/405.jpg',
  'assets/quran/406.jpg',
  'assets/quran/407.jpg',
  'assets/quran/408.jpg',
  'assets/quran/409.jpg',
  'assets/quran/410.jpg',
  'assets/quran/411.jpg',
  'assets/quran/412.jpg',
  'assets/quran/413.jpg',
  'assets/quran/414.jpg',
  'assets/quran/415.jpg',
  'assets/quran/416.jpg',
  'assets/quran/417.jpg',
  'assets/quran/418.jpg',
  'assets/quran/419.jpg',
  'assets/quran/420.jpg',
  'assets/quran/421.jpg',
  'assets/quran/422.jpg',
  'assets/quran/423.jpg',
  'assets/quran/424.jpg',
  'assets/quran/425.jpg',
  'assets/quran/426.jpg',
  'assets/quran/427.jpg',
  'assets/quran/428.jpg',
  'assets/quran/429.jpg',
  'assets/quran/430.jpg',
  'assets/quran/431.jpg',
  'assets/quran/432.jpg',
  'assets/quran/433.jpg',
  'assets/quran/434.jpg',
  'assets/quran/435.jpg',
  'assets/quran/436.jpg',
  'assets/quran/437.jpg',
  'assets/quran/438.jpg',
  'assets/quran/439.jpg',
  'assets/quran/440.jpg',
  'assets/quran/441.jpg',
  'assets/quran/442.jpg',
  'assets/quran/443.jpg',
  'assets/quran/444.jpg',
  'assets/quran/445.jpg',
  'assets/quran/446.jpg',
  'assets/quran/447.jpg',
  'assets/quran/448.jpg',
  'assets/quran/449.jpg',
  'assets/quran/450.jpg',
  'assets/quran/451.jpg',
  'assets/quran/452.jpg',
  'assets/quran/453.jpg',
  'assets/quran/454.jpg',
  'assets/quran/455.jpg',
  'assets/quran/456.jpg',
  'assets/quran/457.jpg',
  'assets/quran/458.jpg',
  'assets/quran/459.jpg',
  'assets/quran/460.jpg',
  'assets/quran/461.jpg',
  'assets/quran/462.jpg',
  'assets/quran/463.jpg',
  'assets/quran/464.jpg',
  'assets/quran/465.jpg',
  'assets/quran/466.jpg',
  'assets/quran/467.jpg',
  'assets/quran/468.jpg',
  'assets/quran/469.jpg',
  'assets/quran/470.jpg',
  'assets/quran/471.jpg',
  'assets/quran/472.jpg',
  'assets/quran/473.jpg',
  'assets/quran/474.jpg',
  'assets/quran/475.jpg',
  'assets/quran/476.jpg',
  'assets/quran/477.jpg',
  'assets/quran/478.jpg',
  'assets/quran/479.jpg',
  'assets/quran/480.jpg',
  'assets/quran/481.jpg',
  'assets/quran/482.jpg',
  'assets/quran/483.jpg',
  'assets/quran/484.jpg',
  'assets/quran/485.jpg',
  'assets/quran/486.jpg',
  'assets/quran/487.jpg',
  'assets/quran/488.jpg',
  'assets/quran/489.jpg',
  'assets/quran/490.jpg',
  'assets/quran/491.jpg',
  'assets/quran/492.jpg',
  'assets/quran/493.jpg',
  'assets/quran/494.jpg',
  'assets/quran/495.jpg',
  'assets/quran/496.jpg',
  'assets/quran/497.jpg',
  'assets/quran/498.jpg',
  'assets/quran/499.jpg',
  'assets/quran/500.jpg',
  'assets/quran/501.jpg',
  'assets/quran/502.jpg',
  'assets/quran/503.jpg',
  'assets/quran/504.jpg',
  'assets/quran/505.jpg',
  'assets/quran/506.jpg',
  'assets/quran/507.jpg',
  'assets/quran/508.jpg',
  'assets/quran/509.jpg',
  'assets/quran/510.jpg',
  'assets/quran/511.jpg',
  'assets/quran/512.jpg',
  'assets/quran/513.jpg',
  'assets/quran/514.jpg',
  'assets/quran/515.jpg',
  'assets/quran/516.jpg',
  'assets/quran/517.jpg',
  'assets/quran/518.jpg',
  'assets/quran/519.jpg',
  'assets/quran/520.jpg',
  'assets/quran/521.jpg',
  'assets/quran/522.jpg',
  'assets/quran/523.jpg',
  'assets/quran/524.jpg',
  'assets/quran/525.jpg',
  'assets/quran/526.jpg',
  'assets/quran/527.jpg',
  'assets/quran/528.jpg',
  'assets/quran/529.jpg',
  'assets/quran/530.jpg',
  'assets/quran/531.jpg',
  'assets/quran/532.jpg',
  'assets/quran/533.jpg',
  'assets/quran/534.jpg',
  'assets/quran/535.jpg',
  'assets/quran/536.jpg',
  'assets/quran/537.jpg',
  'assets/quran/538.jpg',
  'assets/quran/539.jpg',
  'assets/quran/540.jpg',
  'assets/quran/541.jpg',
  'assets/quran/542.jpg',
  'assets/quran/543.jpg',
  'assets/quran/544.jpg',
  'assets/quran/545.jpg',
  'assets/quran/546.jpg',
  'assets/quran/547.jpg',
  'assets/quran/548.jpg',
  'assets/quran/549.jpg',
  'assets/quran/550.jpg',
  'assets/quran/551.jpg',
  'assets/quran/552.jpg',
  'assets/quran/553.jpg',
  'assets/quran/554.jpg',
  'assets/quran/555.jpg',
  'assets/quran/556.jpg',
  'assets/quran/557.jpg',
  'assets/quran/558.jpg',
  'assets/quran/559.jpg',
  'assets/quran/560.jpg',
  'assets/quran/561.jpg',
  'assets/quran/562.jpg',
  'assets/quran/563.jpg',
  'assets/quran/564.jpg',
  'assets/quran/565.jpg',
  'assets/quran/566.jpg',
  'assets/quran/567.jpg',
  'assets/quran/568.jpg',
  'assets/quran/569.jpg',
  'assets/quran/570.jpg',
  'assets/quran/571.jpg',
  'assets/quran/572.jpg',
  'assets/quran/573.jpg',
  'assets/quran/574.jpg',
  'assets/quran/575.jpg',
  'assets/quran/576.jpg',
  'assets/quran/577.jpg',
  'assets/quran/578.jpg',
  'assets/quran/579.jpg',
  'assets/quran/580.jpg',
  'assets/quran/581.jpg',
  'assets/quran/582.jpg',
  'assets/quran/583.jpg',
  'assets/quran/584.jpg',
  'assets/quran/585.jpg',
  'assets/quran/586.jpg',
  'assets/quran/587.jpg',
  'assets/quran/588.jpg',
  'assets/quran/589.jpg',
  'assets/quran/590.jpg',
  'assets/quran/591.jpg',
  'assets/quran/592.jpg',
  'assets/quran/593.jpg',
  'assets/quran/594.jpg',
  'assets/quran/595.jpg',
  'assets/quran/596.jpg',
  'assets/quran/597.jpg',
  'assets/quran/598.jpg',
  'assets/quran/599.jpg',
  'assets/quran/600.jpg',
  'assets/quran/601.jpg',
  'assets/quran/602.jpg',
  'assets/quran/603.jpg',
  'assets/quran/604.jpg',
];
List<String> surahs = [
  'الفاتحة - Al-Fatiha',
  'البقرة - Al-Baqarah',
  'آل عمران - Aal-E-Imran',
  'النساء - An-Nisa\'',
  'المائدة - Al-Ma\'idah',
  'الأنعام - Al-An\'am',
  'الأعراف - Al-A\'raf',
  'الأنفال - Al-Anfal',
  'التوبة - At-Tawbah',
  'يونس - Yunus',
  'هود - Hud',
  'يوسف - Yusuf',
  'الرعد - Ar-Ra\'d',
  'إبراهيم - Ibrahim',
  'الحجر - Al-Hijr',
  'النحل - An-Nahl',
  'الإسراء - Al-Isra\'',
  'الكهف - Al-Kahf',
  'مريم - Maryam',
  'طه - Ta-Ha',
  'الأنبياء - Al-Anbiya\'',
  'الحج - Al-Hajj',
  'المؤمنون - Al-Mu\'minun',
  'النور - An-Nur',
  'الفرقان - Al-Furqan',
  'الشعراء - Ash-Shu\'ara\'',
  'النمل - An-Naml',
  'القصص - Al-Qasas',
  'العنكبوت - Al-Ankabut',
  'الرّوم - Ar-Rum',
  'لقمان - Luqman',
  'السجدة - As-Sajda',
  'الأحزاب - Al-Ahzab',
  'سبأ - Saba\'',
  'فاطر - Fatir',
  'يس - Ya-Sin',
  'الصافات - As-Saffat',
  'ص - Sad',
  'الزمر - Az-Zumar',
  'غافر - Ghafir',
  'فصلت - Fussilat',
  'الشورى - Ash-Shura',
  'الزخرف - Az-Zukhruf',
  'الدخان - Ad-Dukhan',
  'الجاثية - Al-Jathiyah',
  'الأحقاف - Al-Ahqaf',
  'محمد - Muhammad',
  'الفتح - Al-Fath',
  'الحجرات - Al-Hujurat',
  'ق - Qaf',
  'الذاريات - Adh-Dhariyat',
  'الطور - At-Tur',
  'النجم - An-Najm',
  'القمر - Al-Qamar',
  'الرحمن - Ar-Rahman',
  'الواقعة - Al-Waqi\'a',
  'الحديد - Al-Hadid',
  'المجادلة - Al-Mujadila',
  'الحشر - Al-Hashr',
  'الممتحنة - Al-Mumtahanah',
  'الصف - As-Saff',
  'الجمعة - Al-Jumu\'ah',
  'المنافقون - Al-Munafiqun',
  'التغابن - At-Taghabun',
  'الطلاق - At-Talaq',
  'التحريم - At-Tahrim',
  'الملك - Al-Mulk',
  'القلم - Al-Qalam',
  'الحاقة - Al-Haaqqa',
  'المعارج - Al-Ma\'arij',
  'نوح - Nuh',
  'الجن - Al-Jinn',
  'المزمل - Al-Muzzammil',
  'المدثر - Al-Muddathir',
  'القيامة - Al-Qiyama',
  'الإنسان - Al-Insan',
  'المرسلات - Al-Mursalat',
  'النبأ - An-Naba\'',
  'النازعات - An-Nazi\'at',
  'عبس - Abasa',
  'التكوير - At-Takwir',
  'الإنفطار - Al-Infitar',
  'المطففين - Al-Mutaffifin',
  'الإنشقاق - Al-Inshiqaq',
  'البروج - Al-Buruj',
  'الطارق - At-Tariq',
  'الأعلى - Al-A\'la',
  'الغاشية - Al-Ghashiyah',
  'الفجر - Al-Fajr',
  'البلد - Al-Balad',
  'الشمس - Ash-Shams',
  'الليل - Al-Lail',
  'الضحى - Ad-Duha',
  'الشرح - Ash-Sharh',
  'التين - At-Tin',
  'العلق - Al-Alaq',
  'القدر - Al-Qadr',
  'البينة - Al-Bayyina',
  'الزلزلة - Az-Zalzalah',
  'العاديات - Al-Adiyat',
  'القارعة - Al-Qari\'a',
  'التكاثر - At-Takathur',
  'العصر - Al-Asr',
  'الهمزة - Al-Humazah',
  'الفيل - Al-Fil',
  'قريش - Quraysh',
  'الماعون - Al-Ma\'un',
  'الكوثر - Al-Kawthar',
  'الكافرون - Al-Kafirun',
  'النصر - An-Nasr',
  'المسد - Al-Masad',
  'الإخلاص - Al-Ikhlas',
  'الفلق - Al-Falaq',
  'الناس - An-Nas'
];
List numberpagesurah = [
  1,
  2,
  50,
  77,
  106,
  128,
  151,
  177,
  187,
  208,
  221,
  235,
  249,
  255,
  262,
  267,
  282,
  293,
  305,
  312,
  322,
  332,
  342,
  350,
  359,
  367,
  377,
  385,
  396,
  404,
  411,
  415,
  418,
  428,
  434,
  440,
  446,
  453,
  458,
  467,
  477,
  483,
  489,
  496,
  499,
  502,
  507,
  511,
  515,
  518,
  520,
  523,
  526,
  528,
  531,
  534,
  537,
  542,
  545,
  549,
  551,
  553,
  554,
  556,
  558,
  560,
  562,
  564,
  566,
  568,
  570,
  572,
  574,
  575,
  577,
  578,
  580,
  582,
  583,
  585,
  586,
  587,
  587,
  589,
  590,
  591,
  591,
  592,
  593,
  594,
  595,
  595,
  596,
  596,
  597,
  597,
  598,
  598,
  599,
  599,
  600,
  600,
  601,
  601,
  601,
  602,
  602,
  602,
  603,
  603,
  603,
  604,
  604,
  604,
];
